
{%- set pyproject = load_file_data('pyproject.toml') %}
{%- set project = pyproject.get('project', {}) %}
{%- set env_file = load_file_data('environment.yaml') %}

package:
    name: {{ project['name'] }}
    version: {{ project['version'] }}

source:
    path: ../

build:
    # Remove comment from line here below, if your package is pure Python
    # noarch: python
    number: '0'
    script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv || exit 1"

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        # Dependencies as defined in environment.yaml
        # Some names might be different from pypi, so please curate that list manually
        {% for dep in env_file['dependencies'] %}
        - {{ dep }}
        {% endfor %}

about:
    home: {{ project['urls']['Homepage'] }}
    license_file: LICENSE
    summary: {{ project['description'] }}
    doc_url: {{ project['urls']['Documentation'] }}

extra:
    maintainers:
        {% for author in project['authors'] %}
        - "{{ author.name }} <{{ author.email }}>"
        {% endfor %}

