{%- set pyproject = load_file_data('pyproject.toml') %}
{%- set project = pyproject.get('project', {}) %}
{%- set env_file = load_file_data('environment.yaml') %}
{%- set py_min_version = project['requires-python'] %}
{%- set py_build_version = py_min_version | replace('>', '') | replace('=', '') %}

package:
    name: {{ project['name'] }}
    version: {{ project['version'] }}

source:
    path: ../

build:
    # Remove comment from line here below, if your package is pure Python
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed . -vv

requirements:
    host:
        - python {{ py_build_version }}.*
        - pip

    run:
        - python >={{ py_min_version }}
        # Dependencies as defined in environment.yaml
        # Some names might be different from pypi, so please curate that list manually
        {% for dep in env_file['dependencies'] if not dep == "torch" %}
        - {{ dep }}
        {% endfor %}
        - pytorch

about:
    home: {{ project['urls']['Homepage'] }}
    license: {{ project['license'] }}
    summary: {{ project['description'] }}
    doc_url: {{ project['urls']['Documentation'] }}

extra:
    maintainers:
        {% for author in project['authors'] %}
        - "{{ author.name }} <{{ author.email }}>"
        {% endfor %}

